### ISSUE TITLE
LogEvent won't log on Flurry

### ISSUE THREAD

**Issue by xEoDx** [vedi/flurry-bunch-unity3d#1]
Once integrated, the FlurryBunch could successfully Log a new Session on Flurry, but LogEvents are not showing on Flurry dashboard (after 24 hours of delay).

This have been tested using the default FlurryBunch.cs + FlurrySceneController.cs (in the start a new Event is logged).

Device: Android

**Comment by vedi** [comment]
Have a look at the issue:
http://stackoverflow.com/a/18668608/1204329

Maybe it's your case. While I'm adding `onEndSession`, please, get sure that you see event sending in log from Flurry on your device.

**Comment by xEoDx** [comment]
Hi, 
as you say, not ending the session could be the problem. 

About logs:
On Android I logged the following:
FlurrryAgent: "Event count incremented: FlurryEventId"

Thanks for fast reply

**Comment by vedi** [comment]
Please, pull the code.

**Comment by xEoDx** [comment]
Hey,

It seems to work now :) 

Thank you very much.

**Comment by vedi** [comment]
you're welcome
